import Head from 'next/head'
import type { NextPage } from 'next'
import LayoutBlock from '@/components/LayoutBlock'
import TransitionEffect from '@/components/TransitionEffect'
import Contact from '@/components/Contact'
import Experince from '@/components/Experince'
import Projects from './project'
import ModelViewerComponent from '@/components/ModelViewComponent'

 const Home: NextPage = () => {

  return (
    <>
  <TransitionEffect/>
  <Head>
    <title>Otto Kingstedt - Webbdesign & Graphic Design</title>
    <meta name='descripton' content='Generated by create next App' />
  </Head>
  <main className='bg-[#fdffe055]'>
<LayoutBlock className=' pb-20 pt-20 lg:mt-0  max-w-[1280px] m-auto grid grid-cols-2'>
  <div className= 'm-auto md:w-full flex lg:flex-col'>
  <div className='md:text-3xl dark:text-white px-8 w-full'>
       <h1 className='md:text-6xl font-semibold text-2xl lg:leading-[75px]'>Så hjälper vi dig att utveckla din nya webbplats.</h1>
       <div className='mt-10'>
        <p className='font-normal text-xl leading-10 text-gray-500'>Jag hjälper dig som företagare med din nya hemsida på ett strategiskt sätt – från idé och planering till lansering av en professionell och användarvänlig webbplats som stöder dina övergripande affärsmål.
</p>
<button className='bg-black hover:bg-gray-600 text-white font-bold py-2 px-4 rounded text-[20px] mt-10'>Kom igång</button>
       </div>
    </div>
  </div>
  <div className=' overflow-hidden relative'>
  <ModelViewerComponent />
    </div> 
</LayoutBlock>
</main>
<Experince />
<Projects />
<Contact />
</>
  )
}
export default Home
